########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = [
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml",
]

# Repository Name
name = "warp"

########################################################################################################################
# Documentation building
########################################################################################################################

[repo_docs]
#name = "Kit App Template"

# kit-manual doc
[[repo_docs.kit.custom_project]]
name = "kit-app-template"
root = "${root}"
config_path = "${root}/docs/docs.toml"


[repo_docs.kit]
extensions = [
]

########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/target-deps.packman.xml",
]

# Extensions precache
fetch.after_pull_commands = [
]
